{
 "title": "race-timer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "SQL operation times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(race_timer_sql_duration_seconds_sum[$interval]) / rate(race_timer_sql_duration_seconds_count[$interval])) by (query)",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "HTTP response times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(race_timer_http_duration_seconds_sum[$interval]) / rate(race_timer_http_duration_seconds_count[$interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(race_timer_http_status[$interval])) by (path, status)",
     "legendFormat": "{{path}} - {{status}}"
    }
   ]
  }
 ]
}